services:
  db:
    image: postgres:15
    container_name: hostie_db
    restart: always
    environment:
      POSTGRES_USER: hostie
      POSTGRES_PASSWORD: hostie
      POSTGRES_DB: hostie
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./Backend
    container_name: hostie_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
